---
- hosts: ec2
  remote_user: ec2-user
  vars:
    ansible_ssh_private_key_file: ~/.aws/rafaelNunes-saopaulo.pem
    host_key_checking: false  
  tasks:
  - name: "Install Squid"
    yum: name=squid state=present
    sudo: yes

  - name: "Config to allow all"
    lineinfile: "dest=/etc/squid/squid.conf state=present regexp='^http_access deny all' line='http_access allow all'"
    sudo: yes

  - name: "Start Squid"
    service: name=squid state=started
    sudo: yes
